export const uiLayout = {
  articleHeader: 'article-reading-shell mx-auto mb-7 w-full border-b border-article-rule pb-5',
  articleHeaderContentWidth:
    'mx-auto mb-7 w-full max-w-[min(100%,var(--site-reading-measure))] border-b border-article-rule pb-5',
  articleRailLayout: 'article-detail-shell article-detail-grid mx-auto w-full',
  articleRailLayoutCompletion: 'hidden xl:block xl:w-full',
  articleRailLayoutGuide: 'hidden xl:grid xl:w-full xl:h-fit xl:self-start xl:gap-3 xl:sticky xl:top-28',
  articleRailLayoutMain: 'min-w-0 xl:self-start',
  articleRail: 'article-utility-shell relative mx-auto w-full',
  articleSection: 'article-reading-shell mx-auto mt-8 w-full border-t border-article-rule pt-8',
  articleShell: 'article-reading-shell mx-auto mt-5 w-full pb-11',
  articleTagList: 'article-reading-shell mx-auto mt-4 flex w-full flex-wrap gap-2.5 border-t border-article-rule pt-4',
  articleUtilitySection: 'article-utility-shell mx-auto mt-8 w-full border-t border-article-rule pt-8',
  blogFrame:
    'mx-auto w-[min(52rem,calc(100vw-2rem))] md:w-[min(52rem,calc(100vw-3rem))] lg:w-[min(59rem,calc(100vw-3rem))]',
  cardsGrid: 'grid gap-4 md:grid-cols-2',
  compactSection: 'site-content-shell mx-auto mt-4 w-full',
  frame:
    'mx-auto w-[min(72rem,calc(100vw-2rem))] md:w-[min(72rem,calc(100vw-3rem))] lg:w-[min(78rem,calc(100vw-3rem))]',
  linearList: 'grid gap-0',
  metaList: 'flex flex-wrap gap-2.5',
  nextReadsGrid: 'grid gap-4 md:grid-cols-3',
  pageShell: 'mx-auto min-h-screen max-w-232 px-4 pb-16 md:px-6 lg:max-w-248',
  pageShellWide: 'mx-auto min-h-screen max-w-6xl px-4 pb-16 md:px-6 lg:max-w-7xl',
  section: 'mt-6',
  sectionHeader: 'mb-3 flex items-center justify-between gap-4',
  stackGrid: 'grid gap-4',
  titleCardList: 'grid gap-4',
  toolbarIntro: 'flex flex-col items-start gap-1 text-left',
} as const
