export const uiTypography = {
  articleBylineName: 'm-0 font-sans font-bold text-article-heading',
  articleExcerpt: 'm-0 mb-2.5 text-base leading-6 text-article-copy',
  articleKicker: 'm-0 text-sm leading-[1.55] text-article-body',
  articleMeta: 'm-0 text-sm leading-6 text-article-body',
  articleMetaSubtle: 'm-0 text-[0.84rem] leading-6 text-article-body',
  articleTitle:
    'mt-4 mb-1.5 font-sans text-[clamp(2rem,4vw,2.75rem)] font-semibold tracking-[-0.025em] text-article-heading',
  bodyCopy: 'm-0 leading-[1.55] text-site-ink-soft',
  cardDescription: 'm-0 text-[0.84rem] leading-6 text-site-ink-soft',
  cardEyebrow: 'm-0 mb-1 text-[0.68rem] font-bold uppercase tracking-[0.18em] text-site-line-strong',
  cardMeta: 'm-0 text-[0.76rem] font-medium tracking-[0.04em] text-site-ink-muted',
  cardMetaCaps: 'mt-auto text-[0.72rem] uppercase tracking-[0.08em] text-site-ink-muted',
  eyebrow: 'm-0 mb-2 text-[0.72rem] font-bold uppercase tracking-[0.22em] text-site-line-strong',
  eyebrowSentence: 'm-0 text-[0.72rem] font-light tracking-[0.08em] text-site-ink-muted',
  footerLink: 'w-fit font-medium leading-6 text-site-ink transition-colors duration-150 hover:text-site-line-strong',
  heading: 'm-0 font-head text-[clamp(1.7rem,5vw,2.4rem)] font-black tracking-[-0.03em] text-site-ink',
  headingCompact: 'm-0 font-head text-[clamp(1.35rem,4vw,1.9rem)] font-black tracking-[-0.03em] text-site-ink',
  linearItemTitle: 'm-0 text-base font-semibold leading-[1.3]',
  linkCardTitle: 'm-0 text-lg font-semibold leading-[1.25]',
  nextReadTitle: 'm-0 text-[0.98rem] leading-[1.2]',
} as const
