export const testIds = {
  adSlot: (placement: string) => `ad-slot-${placement}`,
  appShell: {
    bottomNav: 'app-shell-bottom-nav',
    compactBackLink: 'app-shell-compact-back-link',
    focusHeader: 'app-shell-focus-header',
    globalHeader: 'app-shell-global-header',
    homeGuidesLink: 'app-shell-home-guides-link',
    homePremiumLink: 'app-shell-home-premium-link',
    homeProgressLink: 'app-shell-home-progress-link',
    homeSettingsLink: 'app-shell-home-settings-link',
    pageIntro: 'app-shell-page-intro',
    primaryNav: 'app-shell-primary-nav',
    themeToggle: 'app-shell-theme-toggle',
  },
  dataControls: {
    exportButton: 'data-controls-export',
    importButton: 'data-controls-import',
    resetAllButton: 'data-controls-reset-all',
    root: 'data-controls-panel',
  },
  deckCard: (deckId: string) => `deck-card-${deckId}`,
  deckCardOpenLink: (deckId: string) => `deck-card-open-${deckId}`,
  deckDetail: {
    continueButton: 'deck-detail-continue',
    interviewButton: 'deck-detail-interview',
    learnMoreLink: (slug: string) => `deck-detail-learn-more-${slug}`,
    learnMoreSection: 'deck-detail-learn-more',
    page: 'deck-detail-page',
    resetButton: 'deck-detail-reset',
    reviewLink: 'deck-detail-review',
    startButton: 'deck-detail-start',
    weakCardsButton: 'deck-detail-weak-cards',
  },
  firstRun: {
    page: 'first-run-panel',
    startDeckLink: (deckId: string) => `first-run-start-${deckId}`,
  },
  home: {
    deckLibrary: 'home-deck-library',
    deckSearch: 'home-deck-search',
    difficultyFilter: (value: string) => `home-difficulty-filter-${value}`,
    page: 'home-page',
    presetCard: (id: string) => `home-preset-card-${id}`,
    presetLink: (id: string) => `home-preset-link-${id}`,
    progressSection: 'home-progress-section',
    statusFilter: (value: string) => `home-status-filter-${value}`,
    trackFilter: (track: string) => `home-track-filter-${track}`,
  },
  install: {
    dismissButton: 'install-panel-dismiss',
    installButton: 'install-panel-install',
    panel: 'install-panel',
  },
  premium: {
    freePlanLink: 'premium-free-plan-link',
    page: 'premium-page',
    previewButton: 'premium-preview-button',
    statusPanel: 'premium-status-panel',
  },
  progress: {
    goalTracker: 'progress-goal-tracker',
    localTools: 'progress-local-tools',
    masterySnapshot: 'progress-mastery-snapshot',
    momentum: 'progress-momentum',
    page: 'progress-page',
    shareCardDownloadButton: 'progress-share-card-download',
    shareCardPanel: 'progress-share-card-panel',
  },
  pwa: {
    panel: 'pwa-status-panel',
    reloadButton: 'pwa-reload-button',
  },
  review: {
    emptyState: 'review-empty-state',
    noteToggle: (cardId: string) => `review-note-${cardId}-toggle`,
    noteTextarea: (cardId: string) => `review-note-${cardId}-textarea`,
    page: 'review-page',
    quickFilter: (mode: string) => `review-quick-filter-${mode}`,
    resetButton: 'review-reset-button',
    searchInput: 'review-search-input',
    statusButton: (cardId: string, status: string) => `review-status-${cardId}-${status}`,
    statusTab: (status: string) => `review-status-tab-${status}`,
    studyWeakCardsLink: 'review-study-weak-cards-link',
    unmarkButton: (cardId: string) => `review-unmark-${cardId}`,
  },
  settings: {
    dailyTarget: (target: number) => `settings-daily-target-${target}`,
    hapticsOff: 'settings-haptics-off',
    hapticsOn: 'settings-haptics-on',
    keepAwake: 'settings-keep-awake',
    letSleep: 'settings-let-sleep',
    page: 'settings-page',
    restoreDefaults: 'settings-restore-defaults',
    timerPreset: (preset: string) => `settings-timer-${preset}`,
    weeklyTarget: (target: number) => `settings-weekly-target-${target}`,
  },
  study: {
    currentStep: 'study-current-step',
    endEarlyButton: 'study-end-early',
    followUpFinish: 'study-follow-up-finish',
    followUpNext: 'study-follow-up-next',
    followUpRunAgain: 'study-follow-up-run-again',
    followUpToggle: 'study-follow-up-toggle',
    learnMoreLink: 'study-learn-more-link',
    learnMoreToggle: 'study-learn-more-toggle',
    noteClear: 'study-note-clear',
    noteTextarea: 'study-note-textarea',
    noteToggle: 'study-note-toggle',
    page: 'study-session-player',
    rateButton: (status: string) => `study-rate-${status}`,
    revealButton: 'study-reveal-answer',
    successPage: 'study-success-page',
    successPrimaryAction: 'study-success-primary-action',
  },
} as const
